[package]
name = "scx_utils"
version = "0.1.0"
edition = "2021"
authors = ["Tejun Heo <tj@kernel.org>"]
license = "GPL-2.0"
repository = "https://github.com/sched-ext/scx"
description = "Utilities for sched_ext schedulers"

[dependencies]
anyhow = "1.0"
regex = "1.10"
sscanf = "0.4"
tar = "0.4"

[build-dependencies]
tar = "0.4"
walkdir = "2.4"
