workspace = { members = ["scx_stats_derive"] }
[package]
name = "scx_stats"
version = "0.1.0"
edition = "2021"
authors = ["Tejun Heo <tj@kernel.org>"]
repository = "https://github.com/sched-ext/scx"
description = "Statistics transport library for sched_ext schedulers"

[dependencies]
anyhow = "1.0"
libc = "0.2"
log = "0.4"
quote = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
syn = { version = "2.0", features = ["extra-traits", "full"] }

[dev-dependencies]
scx_stats_derive = { path = "scx_stats_derive", version = "0.1.0" }
simple_logger = "5.0"
