name: 'Build kernel'
description: 'Build a kernel with Nix and expose the paths as environment variables'
inputs:
  repo-name:
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: Get Nix store path
      run: |
        echo "KERNEL_STORE_PATH=$(nix eval --raw ./.github/include#kernels.'${{ inputs.repo-name }}'.outPath)" >> $GITHUB_ENV
        echo "KERNEL_HEADERS_STORE_PATH=$(nix eval --raw ./.github/include#kernels.'${{ inputs.repo-name }}'.headers.outPath)" >> $GITHUB_ENV
      shell: bash

    - name: Build kernel
      shell: bash
      run: nix build --no-link ./.github/include#kernels.'${{ inputs.repo-name }}'{,.headers}
