name: 6_12-test

on:
  # only runs on main, every 6 hours. specify hours explicitly so scheduled runs can be offset and use a random minute.
  schedule:
    - cron: "46 1,7,13,19 * * *"

jobs:
  build-kernel:
    runs-on: ${{ github.repository_owner == 'sched-ext' && fromJSON('[ "self-hosted", "linux", "x64" ]') || 'ubuntu-latest' }}
    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: ./.github/actions/install-nix
        with:
          cachix-auth-token: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - uses: ./.github/actions/build-kernel
        with:
          repo-name: stable/6_12

  integration-test:
    uses: ./.github/workflows/integration-tests.yml
    needs: build-kernel
    secrets: inherit
    with:
      repo-name: stable/6_12

  notify-job:
    runs-on: ubuntu-latest
    if: ${{ failure() && github.ref == 'refs/heads/main' }}
    needs:
      - integration-test
    steps:
    - uses: actions/checkout@v2
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_USERNAME: ci
        SLACK_ICON: https://www.dictionary.com/e/wp-content/uploads/2018/03/thisisfine-1.jpg
        SLACK_TITLE: Workflow failed
        SLACK_MESSAGE: 6.12 ci job failed.
        SLACK_COLOR: failure
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}

